---
name: LimitCreative
version: 1.0.0
main: ErikPDev\LimitCreative\LimitCreative
api: 4.0.0
src-namespace-prefix: ErikPDev\LimitCreative

permissions:
  limitcreative.bypass:
    description: "Bypass the LimitCreative plugin"
    default: "op"
...
